### ISSUE TITLE
Locating the DeepLab V2 VOC12 Model

### ISSUE THREAD

**Issue by tyrian411** [gmayday1997/SceneChangeDet#6]
Hello,

I'm attempting to get your source working; however, I'm unable to locate a copy of the "deeplab_v2_voc12.pth" pretrained model file.  I've looked on the DeepLab V2 models page (http://liangchiehchen.com/projects/DeepLab_Models.html), but I don't see a model trained on VOC.  Do you have a link to the model file used in your code?

Thanks!

**Comment by ssktotoro** [comment]
under the pretrain section of their README there are links via baidu and google drive for the pretrained model file.
